// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject.Server.Data;

#nullable disable

namespace WebProject.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebProject.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "myemail1@gmail.com",
                            Password = "password1",
                            RefreshToken = "token",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 18, 44, 16, 302, DateTimeKind.Utc).AddTicks(5169),
                            Username = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            Email = "myemail2@gmail.com",
                            Password = "password2",
                            RefreshToken = "token",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 18, 44, 16, 302, DateTimeKind.Utc).AddTicks(5174),
                            Username = "Rick"
                        },
                        new
                        {
                            Id = 3,
                            Email = "myemail3@gmail.com",
                            Password = "password3",
                            RefreshToken = "token",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 18, 44, 16, 302, DateTimeKind.Utc).AddTicks(5176),
                            Username = "John"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
